name: SimpleAuthMe
version: '1.0'
main: com.rookygod.simpleauthme.SimpleAuthMe
api-version: '1.21'
description: A simplified AuthMe-like authentication plugin for Paper 1.21.x
author: rookygod
commands:
  register:
    description: Register a new account
    usage: /register <password>
    aliases: [reg]
  login:
    description: Login to your account
    usage: /login <password>
    aliases: [l]
  changepassword:
    description: Change your password
    usage: /changepassword <old> <new>
    aliases: [changepw, cp]

